// BF_CLIENT_BLOCK_v523_BROKER_IMPORT
import {beforeEach,describe,expect,it} from "vitest";
import {render,renderHook,screen} from "@testing-library/react";
import {__resetSingletonForTests,useApplicationStore} from "../../state/useApplicationStore";
import {annualRevenueBand,applyBrokerImport,fixedAssetsBand,fundingIntent,industryOption,mapBrokerPrefill,monthlyRevenueBand,purposeOption,readBrokerNotice,receivablesBand,structureOption,yearsBand,type BrokerPrefill} from "../brokerPrefill";
import {BrokerImportBanner} from "../../components/BrokerImportBanner";
const sample:BrokerPrefill={kyc:{fundingAmount:250000,purposeOfFunds:"Fonds de roulement",lookingFor:"capital",businessLocation:"Canada",industry:"Entrepreneur en construction",yearsInBusiness:6,annualRevenue:1200000,monthlyRevenue:100000,accountsReceivable:180000,fixedAssets:null},business:{legalName:"9123-4567 Québec inc.",address:"12 rue Principale",city:"Laval",state:"QC",zip:"H7N 1A1",phone:"+15145550101",startDate:"2019-04-01",businessStructure:"Société par actions (inc.)",craBusinessNumber:"1234567890"},applicant:{firstName:"Jean",lastName:"Tremblay",email:"jean@ex.ca",ownership:100}};
describe("broker prefill mapping",()=>{it("maps broker values to wizard options",()=>{expect(annualRevenueBand(1200000)).toBe("$1,000,001 to $3,000,000");expect(monthlyRevenueBand(100000)).toBe("$50,000 to $100,000");expect(receivablesBand(0)).toBe("No Account Receivables");expect(fixedAssetsBand(0)).toBe("None");expect(yearsBand(.5)).toBe("Under 1 Year");expect(fundingIntent("equipment")).toBe("EQUIPMENT");expect(industryOption("Entrepreneur en construction")).toBe("Construction");expect(purposeOption("Fonds de roulement","WORKING_CAPITAL")).toBe("Working Capital");expect(structureOption("Société par actions (inc.)")).toBe("Corporation")});it("lists remaining answers",()=>{const m=mapBrokerPrefill(sample);expect(m.kyc.fundingAmount).toMatch(/250,000/);expect(m.applicant.ownership).toBe("100");expect(m.missing).toEqual(expect.arrayContaining(["Available collateral","Your date of birth","Your home address"]));expect(m.missing).not.toContain("Amount requested")})});
describe("broker wizard loading",()=>{beforeEach(()=>{localStorage.clear();__resetSingletonForTests()});it("loads state and displays notice",()=>{applyBrokerImport("5f0c2a9e-3b1d-4c7e-9a2b-1d2e3f4a5b6c",sample,"Avance");const{result}=renderHook(()=>useApplicationStore());expect(result.current.app.applicationToken).toBe("5f0c2a9e-3b1d-4c7e-9a2b-1d2e3f4a5b6c");expect(readBrokerNotice("5f0c2a9e-3b1d-4c7e-9a2b-1d2e3f4a5b6c")?.brokerName).toBe("Avance");expect(readBrokerNotice("other")).toBeNull();render(<BrokerImportBanner/>);expect(screen.getByTestId("broker-import-banner").textContent).toMatch(/from Avance.*Your date of birth/s)})});
