/* @vitest-environment jsdom */
// BF_CLIENT_BLOCK_v470_CATEGORY_INFO
import { act, type ReactNode } from "react"; import { createRoot, type Root } from "react-dom/client"; import { beforeEach, describe, expect, it, vi } from "vitest"; import { Step2_Product } from "../Step2_Product";
type W={children:ReactNode}; const updateMock=vi.fn(); const navigateMock=vi.fn(); const mk=(id:string,type:string)=>({id,name:id,product_type:type,lender_id:"l-"+id,amount_min:1000,amount_max:200000,required_documents:[] as string[]});
vi.mock("react-router-dom",async()=>({...await vi.importActual("react-router-dom"),useNavigate:()=>navigateMock})); vi.mock("../../state/useApplicationStore",()=>({useApplicationStore:()=>({app:{currentStep:2,kyc:{businessLocation:"United States",fundingAmount:"100000",lookingFor:"Purchase Order Financing"},productRequirements:{},matchPercentages:{},linkedApplicationTokens:[] as string[],applicationToken:"token-parent"},update:updateMock})})); vi.mock("../../api/lenders",()=>({getClientLenderProducts:vi.fn(async()=>[mk("a","LOC"),mk("b","TERM"),mk("c","FACTORING"),mk("d","MCA"),mk("e","EQUIPMENT")])})); vi.mock("../productSelection",()=>({filterActiveProducts:<T,>(x:T[])=>x,buildCategorySummaries:(): unknown[]=>[],groupProductsByLender:(): unknown[]=>[],getMatchingProducts:(): unknown[]=>[],isAmountWithinRange:()=>true,matchesCountry:()=>true,parseCurrencyAmount:()=>100000}));
vi.mock("../../components/StepHeader",()=>({StepHeader:()=> <div/>})); vi.mock("../../components/WizardLayout",()=>({WizardLayout:({children}:W)=><div>{children}</div>})); vi.mock("../../components/ui/Card",()=>({Card:({children}:W)=><div>{children}</div>})); vi.mock("../../components/ui/Button",()=>({Button:({children,...props}:W&Record<string,unknown>)=><button {...props}>{children}</button>})); vi.mock("../../components/ui/EmptyState",()=>({EmptyState:({children}:W)=><div>{children}</div>})); vi.mock("../../components/ui/Spinner",()=>({Spinner:()=> <div/>})); vi.mock("../../applications/linkedApplications",()=>({createLinkedApplication:vi.fn(),LinkedApplicationStore:{has:()=>false}})); vi.mock("../../state/clientProfiles",()=>({ClientProfileStore:{upsertProfile:vi.fn()}})); vi.mock("../../utils/analytics",()=>({trackEvent:vi.fn()})); vi.mock("../../utils/track",()=>({track:vi.fn()})); vi.mock("../saveStepProgress",()=>({persistApplicationStep:vi.fn(async()=>undefined)})); vi.mock("../stepGuard",()=>({resolveStepGuard:()=>2}));
import {CATEGORY_INFO,CATEGORY_INFO_FIELDS} from "../productCategoryInfo"; import {CATEGORY_BUCKETS} from "../categoryAliases";
describe("v470 category descriptions",()=>{it("every category has all five parts filled in",()=>{for(const b of CATEGORY_BUCKETS){const info=CATEGORY_INFO[b.id];expect(info,b.id).toBeTruthy();for(const f of CATEGORY_INFO_FIELDS)expect(String(info[f.key]).length,`${b.id}.${f.key}`).toBeGreaterThan(20);}expect(CATEGORY_INFO_FIELDS.map(f=>f.label)).toEqual(["What it is","What it is usually used for","Terms and interest","Best used for","Not the best choice for"]);});});
describe("v470 Step 2 What is this? and Compare",()=>{let container:HTMLDivElement;let root:Root;const q=(s:string)=>container.querySelector(s) as HTMLElement|null;const click=async(e:HTMLElement|null)=>{await act(async()=>{e?.click();});};beforeEach(async()=>{(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;updateMock.mockReset();container=document.createElement("div");document.body.appendChild(container);root=createRoot(container);await act(async()=>{root.render(<Step2_Product/>);});await act(async()=>{await Promise.resolve();});});it("What is this? opens the five-part description without selecting the category",async()=>{await click(q('[data-testid="step2-info-LINE_OF_CREDIT"]'));const d=q('[data-testid="step2-info-dialog"]');expect(d?.textContent).toContain("Line of Credit");expect(d?.textContent).toContain("Not the best choice for");expect(updateMock.mock.calls.some(([p])=>p&&typeof p==="object"&&"productCategory" in p)).toBe(false);root.unmount();container.remove();});it("Compare needs two ticks, shows a side-by-side table, and stops at four",async()=>{const btn=()=>q('[data-testid="step2-compare-btn"]') as HTMLButtonElement;expect(btn().disabled).toBe(true);await click(q('[data-testid="step2-compare-LINE_OF_CREDIT"]'));await click(q('[data-testid="step2-compare-TERM_LOAN"]'));expect(btn().disabled).toBe(false);await click(btn());const t=q('[data-testid="step2-compare-dialog"] table');expect(t?.textContent).toContain("Line of Credit");expect(t?.querySelectorAll("tbody tr").length).toBe(5);await click(q('[data-testid="step2-compare-FACTORING"]'));await click(q('[data-testid="step2-compare-MERCHANT_CASH_ADVANCE"]'));expect((q('[data-testid="step2-compare-EQUIPMENT_FINANCE"]') as HTMLInputElement).disabled).toBe(true);root.unmount();container.remove();});});
