import { API_ENDPOINTS_CONTRACT, DOCUMENT_CONTRACT } from "@/contracts";

export const API_ENDPOINTS = {
  OTP_START: "/api/auth/otp/start",
  OTP_VERIFY: "/api/auth/otp/verify",
  APPLICATIONS: API_ENDPOINTS_CONTRACT.CLIENT_APPLICATIONS.ROOT,
  DOCUMENT_UPLOAD: DOCUMENT_CONTRACT.UPLOAD,
  TELEPHONY_TOKEN: API_ENDPOINTS_CONTRACT.TELEPHONY.TOKEN
} as const;

export type ApiEndpoint = (typeof API_ENDPOINTS)[keyof typeof API_ENDPOINTS];
