import { API_ENDPOINTS_CONTRACT, AUTH_ENDPOINTS, DOCUMENT_CONTRACT } from "@/contracts";

export const API_ENDPOINTS = {
  OTP_START: AUTH_ENDPOINTS.OTP_START,
  OTP_VERIFY: AUTH_ENDPOINTS.OTP_VERIFY,
  AUTH_ME: API_ENDPOINTS_CONTRACT.AUTH.ME,
  APPLICATIONS: API_ENDPOINTS_CONTRACT.CLIENT_APPLICATIONS.ROOT,
  DOCUMENT_UPLOAD: DOCUMENT_CONTRACT.UPLOAD,
  TELEPHONY_TOKEN: API_ENDPOINTS_CONTRACT.TELEPHONY.TOKEN
} as const;

export type ApiEndpoint = (typeof API_ENDPOINTS)[keyof typeof API_ENDPOINTS];
