// BF_CLIENT_BLOCK_v523_BROKER_IMPORT
import { formatCurrencyValue } from "../utils/location";
import { applyBrokerPrefill } from "../state/useApplicationStore";

type Person={firstName?:string|null;lastName?:string|null;email?:string|null;phone?:string|null;dob?:string|null;street?:string|null;city?:string|null;state?:string|null;zip?:string|null;ownership?:number|null;title?:string|null};
export type BrokerPrefill={kyc?:{fundingAmount?:number|null;purposeOfFunds?:string|null;lookingFor?:string|null;businessLocation?:string|null;industry?:string|null;yearsInBusiness?:number|null;annualRevenue?:number|null;monthlyRevenue?:number|null;accountsReceivable?:number|null;fixedAssets?:number|null};business?:{legalName?:string|null;businessName?:string|null;address?:string|null;city?:string|null;state?:string|null;zip?:string|null;phone?:string|null;website?:string|null;startDate?:string|null;businessStructure?:string|null;employees?:number|null;craBusinessNumber?:string|null;naicsCode?:string|null};applicant?:Person|null;partner?:Person|null};
export const BROKER_NOTICE_KEY="bf_broker_import_notice";
export type BrokerNotice={applicationId:string;brokerName:string;missing:string[]};
const band=(n:number|null|undefined,e:[number,string][],over:string)=>{if(n==null||!Number.isFinite(n)||n<0)return undefined;return e.find(([m])=>n<=m)?.[1]??over};
export const annualRevenueBand=(n?:number|null)=>band(n,[[150000,"Zero to $150,000"],[500000,"$150,001 to $500,000"],[1000000,"$500,001 to $1,000,000"],[3000000,"$1,000,001 to $3,000,000"]],"Over $3,000,000");
export const monthlyRevenueBand=(n?:number|null)=>band(n,[[9999.99,"Under $10,000"],[25000,"$10,000 to $25,000"],[50000,"$25,000 to $50,000"],[100000,"$50,000 to $100,000"],[250000,"$100,000 to $250,000"]],"Over $250,000");
export const receivablesBand=(n?:number|null)=>n===0?"No Account Receivables":band(n,[[100000,"Zero to $100,000"],[250000,"$100,000 to $250,000"],[500000,"$250,000 to $500,000"],[1000000,"$500,000 to $1,000,000"],[3000000,"$1,000,000 to $3,000,000"]],"Over $3,000,000");
export const fixedAssetsBand=(n?:number|null)=>n===0?"None":band(n,[[50000,"$1 to $50,000"],[100000,"$50,001 to $100,000"],[250000,"$100,001 to $250,000"],[500000,"$250,001 to $500,000"]],"Over $500,000");
export const yearsBand=(n?:number|null)=>n==null||!Number.isFinite(n)||n<0?undefined:n===0?"Zero":n<1?"Under 1 Year":n<=3?"1 to 3 Years":"Over 3 Years";
export function fundingIntent(v?:string|null){const t=String(v??"").toLowerCase();if(!t)return;if((/both|&|and/.test(t)&&/equip/.test(t))||/both/.test(t))return"BOTH";if(/equip|[eé]quipement/.test(t))return"EQUIPMENT";if(/capital|working|fonds de roulement|loan|pr[eê]t|credit|cr[eé]dit/.test(t))return"WORKING_CAPITAL";}
const INDUSTRIES:[RegExp,string][]=[[/agri|farm|ferme/i,"Agriculture"],[/auto|garage|m[eé]canique/i,"Auto Sales & Repair"],[/constr|contractor|entrepreneur|b[aâ]timent|r[eé]novation/i,"Construction"],[/educat|school|[eé]cole|formation/i,"Education"],[/energy|[eé]nergie|oil|gas|solar/i,"Energy"],[/health|medical|dental|clinic|pharma|sant[eé]/i,"Healthcare"],[/hotel|h[oô]tel|lodging|hospitality/i,"Hospitality & Lodging"],[/truck|camion|logistic|freight|courier/i,"Logistics & Trucking"],[/manufactur|fabrica|usine|industrial/i,"Manufacturing"],[/salon|spa|fitness|gym|personal service|soins/i,"Personal Services"],[/professional|consult|account|comptab|legal|law|avocat|engineer/i,"Professional Services"],[/real estate|immobili|property/i,"Real Estate"],[/restaurant|food|aliment|caf[eé]|bar|catering/i,"Restaurant/Food Service"],[/retail|store|magasin|boutique/i,"Retail"],[/tech|software|logiciel|informatique|\bit\b|saas/i,"Technology"],[/transport|taxi|bus|aviation/i,"Transportation"],[/wholesale|distribut|grossiste|import|export/i,"Wholesale & Distribution"]];
export function industryOption(v?:string|null){const t=String(v??"");return INDUSTRIES.find(([r])=>r.test(t))?.[1]}
export function purposeOption(v:string|null|undefined,intent:string|undefined){const t=String(v??"").toLowerCase();if(!t)return;if(intent==="EQUIPMENT"){if(/replace|remplac/.test(t))return"Replace Existing Equipment";if(/lease ?back|cession-bail/.test(t))return"Lease Back to access capital";if(/expan|agrand|more|additional/.test(t))return"Purchase more equipment to expand";return"Buy New Equipment"}if(/inventor|stock/.test(t))return"Buy Inventory";if(/receivable|a\/r|comptes? clients|factur/.test(t))return"Funds to cover A/R";if(/expan|agrand|growth|croissance|acqui/.test(t))return"Expansion";if(/working capital|fonds de roulement|cash ?flow|liquidit|operat/.test(t))return"Working Capital";}
export function structureOption(v?:string|null){const t=String(v??"").toLowerCase();if(/non[- ]?profit|sans but lucratif|obnl|osbl/.test(t))return"Non-Profit";if(/s[- ]?corp/.test(t))return"S Corporation";if(/llc/.test(t))return"LLC";if(/sole|propri[eé]taire unique|individu/.test(t))return"Sole Proprietorship";if(/partner|soci[eé]t[eé] en nom/.test(t))return"Partnership";if(/corp|inc|lt[eé]e|ltd|incorpor|soci[eé]t[eé] par actions|compagnie/.test(t))return"Corporation";}
const str=(v:unknown)=>v==null||String(v).trim()===""?undefined:String(v).trim();
const compact=(o:Record<string,unknown>)=>Object.fromEntries(Object.entries(o).filter(([,v])=>v!==undefined));
const person=(p?:Person|null)=>p?compact({...p,firstName:str(p.firstName),lastName:str(p.lastName),fullName:[str(p.firstName),str(p.lastName)].filter(Boolean).join(" ")||undefined,ownership:p.ownership!=null&&Number.isFinite(p.ownership)?String(p.ownership):undefined}):{};
const CHECK:[string,string][]=[["kyc.lookingFor","Type of financing"],["kyc.fundingAmount","Amount requested"],["kyc.businessLocation","Country"],["kyc.industry","Industry"],["kyc.purposeOfFunds","Use of funds"],["kyc.yearsInBusiness","Years in business"],["kyc.annualRevenue","Annual revenue"],["kyc.monthlyRevenue","Monthly revenue"],["kyc.accountsReceivable","Accounts receivable"],["kyc.fixedAssets","Available collateral"],["business.legalName","Business legal name"],["business.address","Business address"],["business.city","Business city"],["business.state","Business province/state"],["business.zip","Business postal code"],["business.phone","Business phone"],["business.startDate","Business start date"],["business.businessStructure","Business structure"],["applicant.firstName","Your first name"],["applicant.lastName","Your last name"],["applicant.email","Your email"],["applicant.dob","Your date of birth"],["applicant.street","Your home address"],["applicant.ownership","Your ownership %"]];
export function mapBrokerPrefill(p?:BrokerPrefill|null){const k=p?.kyc??{},b=p?.business??{},country=k.businessLocation==="United States"?"US":"CA",intent=fundingIntent(k.lookingFor),years=yearsBand(k.yearsInBusiness),ar=receivablesBand(k.accountsReceivable),fixed=fixedAssetsBand(k.fixedAssets),annual=annualRevenueBand(k.annualRevenue),legal=str(b.legalName)??str(b.businessName),applicant=person(p?.applicant),partner=person(p?.partner);const kyc=compact({lookingFor:intent,fundingAmount:k.fundingAmount!=null&&k.fundingAmount>0?formatCurrencyValue(String(k.fundingAmount),country)||undefined:undefined,businessLocation:k.businessLocation==="Canada"||k.businessLocation==="United States"?k.businessLocation:undefined,industry:industryOption(k.industry),purposeOfFunds:purposeOption(k.purposeOfFunds,intent),yearsInBusiness:years,salesHistory:years,annualRevenue:annual,revenueLast12Months:annual,monthlyRevenue:monthlyRevenueBand(k.monthlyRevenue),accountsReceivable:ar,arBalance:ar,fixedAssets:fixed,availableCollateral:fixed,companyName:legal,fullName:applicant.fullName,email:applicant.email,phone:applicant.phone});const business=compact({legalName:legal,businessName:str(b.businessName)??legal,companyName:legal,address:str(b.address),city:str(b.city),state:str(b.state),zip:str(b.zip),phone:str(b.phone),website:str(b.website),startDate:str(b.startDate),businessStructure:structureOption(b.businessStructure),employees:b.employees!=null?String(b.employees):undefined,craBusinessNumber:country==="CA"?str(b.craBusinessNumber):undefined,ein:country==="US"?str(b.craBusinessNumber):undefined,naicsCode:str(b.naicsCode)});const applicantState:Record<string,unknown>={...applicant};if(partner.firstName||partner.lastName){applicantState.hasMultipleOwners=true;applicantState.partner=partner}const groups:Record<string,Record<string,unknown>>={kyc,business,applicant:applicantState};const missing=CHECK.filter(([path])=>{const[g,key]=path.split(".");return groups[g]?.[key]===undefined}).map(([,label])=>label);return{kyc,business,applicant:applicantState,missing}}
export function applyBrokerImport(applicationId:string,prefill:BrokerPrefill|null|undefined,brokerName:string|null|undefined){const mapped=mapBrokerPrefill(prefill);applyBrokerPrefill(applicationId,{kyc:mapped.kyc,business:mapped.business,applicant:mapped.applicant} as never);const notice:BrokerNotice={applicationId,brokerName:str(brokerName)??"your broker",missing:mapped.missing};try{localStorage.setItem(BROKER_NOTICE_KEY,JSON.stringify(notice))}catch{}return notice}
export function readBrokerNotice(token:string|null|undefined):BrokerNotice|null{try{const raw=localStorage.getItem(BROKER_NOTICE_KEY);if(!raw)return null;const n=JSON.parse(raw) as BrokerNotice;return token&&n.applicationId===token?n:null}catch{return null}}
